Q.5: We will required alpha value for performing the test.<br>

In [149]:
### Loading the data
import pandas as pd
import numpy as np
exam_data = pd.read_csv('ExamData_1812.csv')

In [165]:
exam_data.where(exam_data.annual_income==55000).dropna()

,Id,sex,annual_income,monthly_expenses,home_ownership,water_availabity,loan_tenure,loan_installments,loan_amount
328,329.0,F,55000.0,4000.0,1.0,0.5,12.0,12.0,5000.0
333,334.0,F,55000.0,4500.0,1.0,0.5,12.0,12.0,5000.0
1116,1117.0,F,55000.0,4000.0,1.0,0.5,12.0,12.0,4000.0
4544,4545.0,M,55000.0,4000.0,1.0,0.5,12.0,12.0,5000.0
5000,5001.0,M,55000.0,3500.0,1.0,0.5,12.0,12.0,5000.0
5030,5031.0,M,55000.0,3500.0,0.0,0.5,12.0,12.0,5000.0
5155,5156.0,F,55000.0,3500.0,0.0,0.5,12.0,12.0,5000.0
6095,6096.0,M,55000.0,3500.0,1.0,0.5,12.0,12.0,5000.0
6541,6542.0,M,55000.0,3500.0,1.0,0.5,12.0,12.0,5000.0
6547,6548.0,F,55000.0,4000.0,1.0,0.5,12.0,12.0,5000.0
6798,6799.0,F,55000.0,1500.0,1.0,0.5,12.0,12.0,5000.0
7449,7450.0,F,55000.0,4000.0,1.0,0.5,12.0,12.0,5000.0
13664,13665.0,F,55000.0,3500.0,1.0,0.5,12.0,12.0,5000.0
14421,14422.0,F,55000.0,3800.0,1.0,0.5,12.0,12.0,5000.0
14427,14428.0,F,55000.0,3500.0,1.0,1.0,12.0,12.0,5000.0
15254,15255.0,F,55000.0,3500.0,0.0,1.0,12.0,50.0,10000.0
15574,15575.0,F,55000.0,2500.0,1.0,1.0,12.0,12.0,5000.0
15576,15577.0,F,55000.0,2500.0,1.0,0.5,12.0,12.0,5000.0
16053,16054.0,F,55000.0,3500.0,1.0,1.0,12.0,12.0,5000.0
16054,16055.0,F,55000.0,3500.0,1.0,1.0,12.0,12.0,5000.0
16317,16318.0,F,55000.0,3000.0,1.0,1.0,12.0,12.0,10000.0
17676,17677.0,F,55000.0,4000.0,1.0,1.0,12.0,12.0,5000.0
17679,17680.0,F,55000.0,4000.0,1.0,0.5,12.0,12.0,5000.0
17765,17766.0,M,55000.0,4000.0,1.0,1.0,12.0,12.0,8000.0
18512,18513.0,F,55000.0,3000.0,1.0,1.0,12.0,12.0,5000.0
18730,18731.0,F,55000.0,4000.0,1.0,1.0,12.0,12.0,5000.0
19553,19554.0,F,55000.0,3500.0,1.0,1.0,12.0,12.0,5000.0
19576,19577.0,F,55000.0,4000.0,1.0,1.0,12.0,12.0,5000.0
19778,19779.0,F,55000.0,4300.0,1.0,1.0,12.0,12.0,5000.0
19882,19883.0,F,55000.0,3000.0,1.0,0.5,12.0,12.0,5000.0
...,...,...,...,...,...,...,...,...,...
38761,38762.0,F,55000.0,1000.0,1.0,0.5,12.0,12.0,8000.0
38772,38773.0,F,55000.0,1000.0,1.0,0.5,12.0,12.0,8000.0
39126,39127.0,F,55000.0,3700.0,1.0,0.5,6.0,6.0,6000.0
39207,39208.0,F,55000.0,3700.0,1.0,0.5,6.0,6.0,6000.0
39258,39259.0,F,55000.0,3450.0,1.0,0.5,6.0,6.0,6000.0
39368,39369.0,F,55000.0,3833.0,1.0,0.5,6.0,6.0,6000.0
39370,39371.0,F,55000.0,3833.0,1.0,0.5,6.0,6.0,6000.0
39372,39373.0,F,55000.0,3333.0,1.0,0.5,6.0,6.0,6000.0
39403,39404.0,F,55000.0,4500.0,1.0,0.5,6.0,6.0,6000.0
39423,39424.0,F,55000.0,4500.0,1.0,0.5,6.0,6.0,6000.0
39446,39447.0,F,55000.0,3833.0,1.0,0.5,6.0,6.0,6000.0
39448,39449.0,F,55000.0,4500.0,1.0,0.5,6.0,6.0,6000.0
39451,39452.0,F,55000.0,4500.0,1.0,0.5,6.0,6.0,6000.0
39459,39460.0,F,55000.0,3667.0,1.0,0.5,6.0,6.0,6000.0
39492,39493.0,F,55000.0,4000.0,1.0,0.5,6.0,6.0,6000.0
39496,39497.0,F,55000.0,4500.0,1.0,0.5,6.0,6.0,6000.0
39511,39512.0,F,55000.0,3750.0,1.0,0.5,6.0,6.0,6000.0
39656,39657.0,F,55000.0,4500.0,1.0,0.5,6.0,6.0,6000.0
39682,39683.0,F,55000.0,3833.0,1.0,0.5,6.0,6.0,6000.0
39684,39685.0,F,55000.0,4417.0,1.0,0.5,6.0,6.0,7000.0
39707,39708.0,F,55000.0,3583.0,1.0,0.5,6.0,6.0,6000.0
39720,39721.0,F,55000.0,4167.0,1.0,0.5,6.0,6.0,6000.0
39725,39726.0,F,55000.0,3583.0,1.0,0.5,6.0,6.0,6000.0
39732,39733.0,F,55000.0,3583.0,1.0,0.5,6.0,6.0,6000.0
39835,39836.0,F,55000.0,3917.0,1.0,0.5,6.0,6.0,6000.0
39838,39839.0,F,55000.0,3833.0,1.0,0.5,6.0,6.0,6000.0
39842,39843.0,F,55000.0,3833.0,1.0,0.5,6.0,6.0,6000.0
39843,39844.0,F,55000.0,4500.0,1.0,0.5,6.0,6.0,6000.0
39866,39867.0,F,55000.0,3833.0,1.0,0.5,6.0,6.0,6000.0
39962,39963.0,F,55000.0,3917.0,1.0,0.5,6.0,6.0,6000.0

This is data of people applied for loan and have received the loan from the institute.<br>
Hence loan_amount is the dependent variable and rest of the attributes are independent attributes.<br>
Based on the available data we need find if the new customers apply's for loan then what would be the eligible amount loaned to him or her<br>

Since Id is independent for any other variable and it is just used to identify the record we can drop the id column<br>
Water_availabity is no where related to person's eligibility for loan, hence we can even drop this colum as well.<br>
Since loan_tenure and loan_installments will be decided after the person is elligible for loan these variable will not play any role here in finding the elligibility of a person for loan hence we can drop these columns as well<br>

In [140]:
exam_data.drop(['Id','water_availabity','loan_tenure','loan_installments'],inplace=True,axis=1)

In [141]:
exam_data['monthly_expenses'].fillna(exam_data.monthly_expenses.mode()[0],inplace=True)
exam_data.home_ownership.fillna(-1,inplace=True) #Assuming the people applied for loan dont own a house

In [142]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
exam_data['sex'] = le.fit_transform(exam_data['sex'])
# exam_data=exam_data.where(exam_data.sex=='F').dropna()
# exam_data.sex=1

In [143]:
exam_data.isna().sum()

sex                 0
annual_income       0
monthly_expenses    0
home_ownership      0
loan_amount         0
dtype: int64

In [145]:
X = exam_data.drop(['loan_amount'],axis=1)
y = exam_data['loan_amount']
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.05,random_state=0)
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(xtrain,ytrain)
pred=linreg.predict(xtest)

In [146]:
shilpa_rec={'sex':[0],'annual_income':[55000],'monthly_expenses':[3500],'home_ownership':[0]}
shilpa=pd.DataFrame(shilpa_rec)

In [147]:
linreg.predict(shilpa)

array([8768.69572959])

In [148]:
from sklearn.metrics import mean_squared_error
lin_rmse = np.sqrt(mean_squared_error(ytest,pred))
lin_rmse

2910.0170820871003